---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 2020 -  Semester 1

Here's your roadmap for the semester! Class materials will be added on the day of the class.

📊 Week 1: [Introduction to data visualization: Visualisation design process](/slides/l12020.html) 

📊 Week 2: [Scientific design choices in data visualization](/slides/lesson2viz.html)

📊 Week 3: [Introduction to the grammar of graphics](/slides/lesson3viz.html)


📊 Week 4: [Introduction to the ggplot2 package](/slides/lecture4dataviz.html)

📊 Week 5: [Visualisation of time series data - Introduction](/slides/lecture5ts.html)

To be continued in Week 11.

#### COVID-19 outbreak

```difff

! Please go to Google Classroom for up-to-date information and announcements.

```

📊 Week 6: [Data wrangling](/datawrangling_tutorial.pdf)

📊 Week 7: [Coordinate systems and axes](/slides/lecture7.html)

📊 Week 8: [Visualizing distributions of data](/slides/lecture8.html)

📊 Week 9: [Create different types of static graphics with ggplot2: categorical Data](/slides/Data_visualization_9.html)

📊 Week 10: [Higher-dimensional displays and special structures](/slides/lecture10.html)

📊 Week 11: [Visualization of time series data](/slides/lesson11tsviz.html)

📊 Week 12: [Principal component analysis](/slides/lesson12pca.html)


📊 Week 13:  [Linked data views of visual exploration/ Dashboard, interactive and animated displays](/slides/lectureplotly.html)

[Example dashboard](https://thiyanga.netlify.app/post/covid19/)

[Example dashboard](/slides/dashboard_penguins.html)

📊 Week 14: Recap - Completed 

📊 Week 15: [Visualization of spatial data](/slides/spatiotemporal.html)
