---
title: "ASP 460 2.0 Special Topics in Statistics"
subtitle: "Interactive graphics"
author: "Thiyanga Talagala"
date: "2020-06-26"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: 
      - default
      - default-fonts
      - duke-blue
      - hygge-duke
      - libs/cc-fonts.css
      - libs/figure-captions.css
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---
```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```

# Spatial data

A spatial process in $d=2$ dimensions is denoted as

$$\{Z(s): s \in D \subset ^d \}$$

$Z$ - observed variable

$s$ - location

## Types of spation data

- Areal (Lattice)

- Geostatistical 

- Point pattern

---
# Areal data

```{r, comment=NA, message=FALSE}
library(sf)
library(ggplot2)
library(viridis)
nc <- st_read(system.file("shape/nc.shp", package = "sf"),
  quiet = TRUE
)
ggplot(data = nc, aes(fill = SID74)) + geom_sf() +
  scale_fill_viridis() + theme_bw()

```

